#pragma once

#define OPENGL_VERSION_MAJOR 4
#define OPENGL_VERSION_MINOR 3
#define OPENGL_VERSION (OPENGL_VERSION_MAJOR * 10 + OPENGL_VERSION_MINOR)

#define OPENGL_DEBUG_ENABLE 1
#define OPENGL_DEBUG (OPENGL_DEBUG_ENABLE && (OPENGL_VERSION >= 43))
